export const BASE_REGIONS = [
  {
    id: 'tutorial',
    name: 'Battle Academy',
    desc: 'Welcome, Commander. Earth is gone. The remnant fleets have scattered. Before we can mount a counter-offensive to reclaim our home, you must prove you can lead a squad. This is a basic simulation.',
    objective: 'Complete training and familiarize yourself with combat mechanics.',
    conditions: 'Controlled simulation environment. Holographic targets.',
    mapId: 'sector_alpha',
    enemyClasses: ['Assault'],
    briefing: 'This is a training exercise. The enemy units are holograms — they fight back, but at reduced effectiveness. Focus on learning movement, cover, and abilities.',
  },
  {
    id: 'sector-1',
    name: 'Outpost Delta',
    desc: 'You passed the trials. Our intel shows a small recon detachment of the Supreme Tactical AI has landed on a resource planet on the fringes of Sector 1. Take them out before they can alert the fleet.',
    reward: 'Unlock Class: Heavy',
    objective: 'Eliminate all hostile forces established at Outpost Delta.',
    conditions: 'Standard visual range. Enemy utilizing recon classes.',
    mapId: 'fort_echo',
    enemyClasses: ['Scout', 'Sniper', 'Assault'],
    briefing: 'Intel suggests a light recon team — Scouts and Snipers mostly. They are fast but fragile. Use cover and close the distance before their Snipers lock on.',
  },
  {
    id: 'sector-2',
    name: 'Neon District',
    desc: 'The scouts were a diversion. We tracked their signal to an abandoned urban mining colony. It is heavily polluted. The enemy is using the smog as cover to harvest the reactors.',
    objective: 'Clear the sector of hostile presence to protect the reactor.',
    conditions: 'Smog Cover Active: Targeting visibility reduced. Expect close-quarters engagement.',
    mapId: 'neon_alley',
    enemyClasses: ['Shotgunner', 'Demoman', 'Assassin', 'Scout'],
    briefing: 'Urban warfare in dense smog. Visibility is severely limited — enemies will try to ambush at close range. Bring Shotgunners and watch for Assassins flanking through the alleys.',
  },
  {
    id: 'sector-3',
    name: 'The Citadel',
    desc: 'With the reactor secure, we have enough power to breach their forward operating base. This citadel is heavily fortified and serves as their local command hub.',
    objective: 'Breach the fortress and secure the zone.',
    conditions: 'Heavily fortified. Enemy squad size increased (+1 unit). AI tactics improved.',
    mapId: 'iron_fortress',
    enemyClasses: ['Heavy', 'Medic', 'Technician', 'Sniper'],
    briefing: 'The Citadel is built like a bunker. Expect Heavies behind Technician cover with Medic support. Take out the Medic first or they will outheal your damage. The Sniper covers the main approach.',
  },
  {
    id: 'sector-4',
    name: 'Frozen Tundra',
    desc: 'We extracted data from the Citadel. It points to a massive cryo-storage facility on the ice world of Kaelen. The enemy is guarding something critical in the deep freeze. Do not let them hold it.',
    objective: 'Survive the assault and eliminate all targets.',
    conditions: 'Extreme cold. Enemy relies heavily on durable classes. +10 HP to all enemies.',
    mapId: 'frozen_outpost',
    enemyClasses: ['Heavy', 'Vanguard', 'Flamethrower', 'Medic', 'Support'],
    briefing: 'The cold has hardened these units — they have bonus HP. The enemy composition is tank-heavy: Vanguards will charge your lines while Flamethrowers close in. Keep your distance and focus fire.',
  },
  {
    id: 'sector-5',
    name: 'Jungle Canopy',
    desc: 'The data retrieved from Kaelen contained the coordinates to their stealth research outpost hidden beneath the dense canopy of Veridia. Expect ambushes.',
    objective: 'Root out the elite hostile squads hidden in the canopy.',
    conditions: 'Smog Cover Active: Thick jungle canopy limits sight lines. Assassins deployed.',
    mapId: 'silent_valley',
    enemyClasses: ['Assassin', 'Scout', 'Phantom', 'Sniper'],
    briefing: 'This is an ambush sector. The canopy blocks sight lines — perfect for Assassins and Phantoms. Deploy Scouts to detect invisible units and keep your squad tight. Isolated units will be picked off.',
  },
  {
    id: 'sector-6',
    name: 'Volcanic Ridge',
    desc: 'They are constructing a dreadnought using the geothermal vents of this volcanic ridge. We must strike now before the ship launches. The enemy has deployed heavy ordinance to defend the construction.',
    objective: 'Overcome the heavy ordinance team.',
    conditions: 'Fire hazard tiles. Elite enemy classes with +15 HP bonus.',
    mapId: 'inferno_pit',
    enemyClasses: ['Flamethrower', 'Demoman', 'Heavy', 'Vanguard', 'Technician'],
    briefing: 'The volcanic terrain is dotted with fire tiles — watch your footing. The enemy has deployed Flamethrowers and Demomen to exploit the terrain. Bring long-range units to fight from safety.',
  },
  {
    id: 'sector-7',
    name: 'Desert Ruin',
    desc: 'Our forces are spread thin. The Supreme AI has sent assassins to a neutral diplomatic ruin to wipe out our allies. Drop in and intercept them.',
    objective: 'Secure the ruins against high-lethality operatives.',
    conditions: 'Smog Cover Active: Airborne sand limits vision. Elite Assassin squads.',
    mapId: 'wasteland_dunes',
    enemyClasses: ['Assassin', 'Assassin', 'Phantom', 'Flamethrower', 'Heavy'],
    briefing: 'Double Assassin deployment confirmed. They will use the sandstorm to vanish and strike. Keep your Medic alive — the burst damage will be extreme. Vanguards and Heavies can absorb the initial strikes.',
  },
  {
    id: 'sector-8',
    name: 'Oceanic Platform',
    desc: 'The enemy fleet is rallying at this offshore command rig. If we take it down, we sever their communication network entirely, clearing the path to their command.',
    objective: 'Neutralize the command rig garrison.',
    conditions: 'Isolated platform. Elite enemy presence with +20 HP bonus. AI fully tactical.',
    mapId: 'orbital_platform',
    enemyClasses: ['Sniper', 'Heavy', 'Support', 'Medic', 'Phantom', 'Demoman'],
    briefing: 'This is their most fortified non-command position. The enemy has a complete tactical composition with Snipers covering lanes, Supports draining your AP, and Phantoms disabling abilities. Bring your best squad.',
  },
  {
    id: 'sector-9',
    name: 'Orbital Command',
    desc: 'This is it, Commander. The Supreme Tactical AI core is aboard the Orbital Command station. We are throwing everything at them. If we win here, the war is won.',
    objective: 'Dismantle the supreme tactical AI forces.',
    conditions: 'Smog Cover Active. Maximum enemy threat level. +25 HP to all enemies. Enemy squad +3 units.',
    mapId: 'omega_station',
    enemyClasses: ['Heavy', 'Assassin', 'Sniper', 'Flamethrower', 'Demoman', 'Medic', 'Phantom', 'Vanguard'],
    briefing: 'The Supreme AI has deployed every class at maximum strength. They outnumber you, they outgun you, and they have tactical superiority. There is no margin for error. This is the final battle, Commander. Make it count.',
  },

  // ─── ACT 2: THE RECLAMATION ───────────────────────────────────────
  {
    id: 'sector-10',
    name: 'The Aftermath',
    desc: 'The Supreme AI is destroyed — but its death triggered a deadman protocol. Autonomous war factories across the galaxy have activated, producing endless drone armies. We intercepted a signal from a crashed carrier on the moon of Tethys. It holds the master shutdown codes.',
    objective: 'Secure the crash site and recover the encryption drive.',
    conditions: 'Drone reinforcements arrive every 3 turns. Enemy squad +1 unit.',
    mapId: 'cathedral_ruins',
    enemyClasses: ['Scout', 'Scout', 'Assault', 'Assault', 'Technician'],
    briefing: 'The crash site is lightly defended — for now. Drone waves will arrive every few turns from the north. Move fast, secure the area, and eliminate all hostiles before reinforcements overwhelm you. Speed is survival.',
  },
  {
    id: 'sector-11',
    name: 'Blackout Depths',
    desc: 'The encryption drive is damaged. Our engineers say the decryption matrix is stored in a deep-space relay station that lost power decades ago. We are going in blind — no scanners, no comms, no backup.',
    objective: 'Navigate the powered-down station and eliminate the defense garrison.',
    conditions: 'Smog Cover Active: Total darkness — all units have reduced vision. No minimap.',
    mapId: 'blackout_station',
    enemyClasses: ['Assassin', 'Phantom', 'Phantom', 'Scout', 'Shotgunner'],
    briefing: 'Zero visibility. The station is pitch black and crawling with Phantoms and Assassins. Your Scout\'s visor is the only reliable detection. Keep the squad tight, move methodically, and do not let anyone get isolated.',
  },
  {
    id: 'sector-12',
    name: 'Foundry Siege',
    desc: 'We have the decryption matrix but the nearest active war factory is on Kragmore — a forge world producing drone armies around the clock. We need to fight through the assembly lines to reach the core transmitter.',
    objective: 'Push through the factory floor and destroy the production garrison.',
    conditions: 'Fire hazard tiles from molten metal. +15 HP to all enemies. Enemy squad +2 units.',
    mapId: 'molten_foundry',
    enemyClasses: ['Heavy', 'Heavy', 'Flamethrower', 'Vanguard', 'Demoman', 'Technician'],
    briefing: 'The foundry floor is lined with molten channels — watch your step. The garrison is tank-heavy with double Heavies and a Vanguard. Flamethrowers will try to push you into the fire lanes. Bring long-range damage and stay mobile.',
  },
  {
    id: 'sector-13',
    name: 'Signal Spire',
    desc: 'The factory is silenced but the drone armies are still active — they are operating on a cached directive. A massive signal spire on the ice moon of Korrath is broadcasting the attack orders. Destroy the garrison and we can upload the shutdown codes.',
    objective: 'Eliminate the spire defense force to gain transmitter access.',
    conditions: 'Extreme cold: +10 HP to all enemies. Poison tiles from cryo-coolant leaks.',
    mapId: 'frozen_spire',
    enemyClasses: ['Sniper', 'Sniper', 'Support', 'Medic', 'Heavy', 'Phantom'],
    briefing: 'The spire is defended by a precision team — double Snipers with Support draining your AP and a Phantom disabling abilities. The cryo-coolant leaks create poison zones. Close the distance fast or get picked apart at range.',
  },
  {
    id: 'sector-14',
    name: 'The Gauntlet Run',
    desc: 'The shutdown codes are uploaded but the signal needs 5 minutes to propagate. The remaining drone forces have converged on our position for a final desperate assault. Hold the line, Commander.',
    objective: 'Survive the onslaught and eliminate all attackers.',
    conditions: 'Smog Cover Active. +20 HP to all enemies. Enemy squad +3 units. Fire and poison hazards.',
    mapId: 'the_gauntlet',
    enemyClasses: ['Vanguard', 'Vanguard', 'Assassin', 'Flamethrower', 'Demoman', 'Shotgunner', 'Scout'],
    briefing: 'They are throwing everything at you — double Vanguards charging through fire and poison corridors with Assassins flanking. The gauntlet is a meat grinder. Hold your ground, use the terrain, and survive.',
  },
  {
    id: 'sector-15',
    name: 'Earth Reclaimed',
    desc: 'The drone armies are shutting down across the galaxy. But one final stronghold remains — Earth itself. A rogue AI fragment has fortified our homeworld with the last operational garrison. Take it back, Commander. Take us home.',
    objective: 'Liberate Earth. Eliminate the final rogue AI garrison.',
    conditions: 'Smog Cover Active. Maximum threat. +30 HP to all enemies. Enemy squad +4 units. All hazard types active.',
    mapId: 'earth_citadel',
    enemyClasses: ['Heavy', 'Assassin', 'Sniper', 'Flamethrower', 'Demoman', 'Medic', 'Phantom', 'Vanguard', 'Support'],
    briefing: 'This is the true final battle. The rogue AI has every class at maximum strength with bonus HP, outnumbering you severely. Fire, poison, and explosives litter the battlefield. There are no second chances. Win here, and humanity reclaims its home. Godspeed, Commander.',
  },
];
